/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * M2C Modula-2 Compiler & Translator                                        *
 *                                                                           *
 * Copyright (c) 2015-2023 Benjamin Kowarsch                                 *
 *                                                                           *
 * @synopsis                                                                 *
 *                                                                           *
 * M2C is a portable  Modula-2 to C translator  and  via-C compiler  for the *
 * bootstrap subset of the revised Modula-2 language described in            *
 *                                                                           *
 * https://github.com/m2sf/m2bsk/wiki/Language-Specification                 *
 *                                                                           *
 * In translator mode,  M2C translates Modula-2 source files to semantically *
 * equivalent C source files.  In compiler mode,  it translates the Modula-2 *
 * source files  to C,  then compiles the resulting C sources  to object and *
 * executable files using the host system's resident C compiler and linker.  *
 *                                                                           *
 * Further information at https://github.com/m2sf/m2c/wiki                   *
 *                                                                           *
 * @file                                                                     *
 *                                                                           *
 * gen-follow-sets.c                                                         *
 *                                                                           *
 * Utility program to generate FOLLOW set literals.                          *
 *                                                                           *
 * @license                                                                  *
 *                                                                           *
 * M2C is free software:  You can redistribute and modify it under the terms *
 * of the GNU Lesser General Public License (LGPL)  either version 2.1 or at *
 * your choice version 3, both published by the Free Software Foundation.    *
 *                                                                           *
 * M2C is distributed in the hope it may be useful, but strictly WITHOUT ANY *
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS *
 * FOR ANY PARTICULAR PURPOSE.  Read the license for more details.           *
 *                                                                           *
 * You should have received  a copy of the GNU Lesser General Public License *
 * along with M2C.  If not, see <https://www.gnu.org/copyleft/lesser.html>.  *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

/* --------------------------------------------------------------------------
 * imports
 * ----------------------------------------------------------------------- */

#import "tokenset.h"
#import <stdio.h>


/* --------------------------------------------------------------------------
 * macros
 * ----------------------------------------------------------------------- */

#define PRINT_PREAMBLE \
  printf("/* AUTO-GENERATED by utility gen-follow-sets * DO NOT EDIT! */\n\n")

#define PRINT_LITERAL(_name, _set) \
  if (m2c_tokenset_element_count(_set) > 1) {
    printf("/* %s */", _name); \
    m2c_tokenset_print_literal(_set); \
    printf(",\n") \
  } /* end if */

#define PRINT_EOF \
  printf("\n/* END OF FILE */\n")


/* --------------------------------------------------------------------------
 * utility program gen-follow-sets
 * --------------------------------------------------------------------------
 * This utility prints a comma delimited list of FOLLOW set literals to the
 * console. It should be invoked with output redirection as follows:
 *
 * $ gen-follow-sets > m2c-follow-set-literals.h
 * ----------------------------------------------------------------------- */

int main() {

PRINT_PREAMBLE;

/* FOLLOW(compilationUnit) */

m2c_tokenset_t compilationUnit = m2c_new_tokenset_from_list(
  TOKEN_EOF, 0
);

PRINT_LITERAL("compilationUnit", compilationUnit);


/* FOLLOW(definitionModule) */

m2c_tokenset_t definitionModule = m2c_new_tokenset_from_list(
  TOKEN_EOF, 0
);

PRINT_LITERAL("definitionModule", definitionModule);


/* FOLLOW(import) */

m2c_tokenset_t import = m2c_new_tokenset_from_list(
  TOKEN_IMPORT, TOKEN_CONST, TOKEN_TYPE, TOKEN_VAR, TOKEN_PROCEDURE,
  TOKEN_TO, TOKEN_END, 0
);

PRINT_LITERAL("import", import);


/* FOLLOW(definition) */

m2c_tokenset_t definition = m2c_new_tokenset_from_list(
  TOKEN_CONST, TOKEN_TYPE, TOKEN_VAR, TOKEN_PROCEDURE, TOKEN_TO, 0
);

PRINT_LITERAL("definition", definition);


/* FOLLOW(constDefinition) */

m2c_tokenset_t constDefinition = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, 0
);

PRINT_LITERAL("constDefinition", constDefinition);


/* FOLLOW(constantBinding) */

m2c_tokenset_t constantBinding = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, 0
);

PRINT_LITERAL("constantBinding", constantBinding);


/* FOLLOW(constDeclaration) */

m2c_tokenset_t constDeclaration = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, 0
);

PRINT_LITERAL("constDeclaration", constDeclaration);


/* FOLLOW(constExpression) */

m2c_tokenset_t constExpression = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_DOT_DOT, TOKEN_RBRACKET, TOKEN_OF, TOKEN_COMMA,
  TOKEN_COLON, TOKEN_RBRACE, 0
);

PRINT_LITERAL("constExpression", constExpression);


/* FOLLOW(typeDefinition) */

m2c_tokenset_t typeDefinition = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, 0
);

PRINT_LITERAL("typeDefinition", typeDefinition);


/* FOLLOW(aliasType) */

m2c_tokenset_t aliasType = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, 0
);

PRINT_LITERAL("aliasType", aliasType);


/* FOLLOW(qualident) */

m2c_tokenset_t qualident = m2c_new_tokenset_from_list(
  TOKEN_DOT, TOKEN_COMMA, TOKEN_SEMICOLON, TOKEN_LPAREN, TOKEN_RPAREN,
  TOKEN_LBRACKET, TOKEN_WILDCARD, TOKEN_DEREF, TOKENDO, TOKEN_END, 0
);

PRINT_LITERAL("qualident", qualident);


/* FOLLOW(subrangeType) */

m2c_tokenset_t subrangeType = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_END, 0
);

PRINT_LITERAL("subrangeType", subrangeType);


/* FOLLOW(constRange) */

m2c_tokenset_t constRange = m2c_new_tokenset_from_list(
  TOKEN_OF, 0
);

PRINT_LITERAL("constRange", constRange);


/* FOLLOW(enumType) */

m2c_tokenset_t enumType = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, 0
);

PRINT_LITERAL("enumType", enumType);


/* FOLLOW(identList) */

m2c_tokenset_t identList = m2c_new_tokenset_from_list(
  TOKEN_COLON, TOKEN_RPAREN, 0
);

PRINT_LITERAL("identList", identList);


/* FOLLOW(setType) */

m2c_tokenset_t setType = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, 0
);

PRINT_LITERAL("setType", setType);


/* FOLLOW(arrayType) */

m2c_tokenset_t arrayType = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_END, 0
);

PRINT_LITERAL("arrayType", arrayType);


/* FOLLOW(recordType) */

m2c_tokenset_t recordType = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, 0
);

PRINT_LITERAL("recordType", recordType);


/* FOLLOW(recTypeToExtend) */

m2c_tokenset_t recTypeToExtend = m2c_new_tokenset_from_list(
  TOKEN_COMMA, 0
);

PRINT_LITERAL("recTypeToExtend", recTypeToExtend);


/* FOLLOW(fieldList) */

m2c_tokenset_t fieldList = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_END, 0
);

PRINT_LITERAL("fieldList", fieldList);


/* FOLLOW(pointerType) */

m2c_tokenset_t pointerType = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, 0
);

PRINT_LITERAL("pointerType", pointerType);


/* FOLLOW(opaqueType) */

m2c_tokenset_t opaqueType = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, 0
);

PRINT_LITERAL("opaqueType", opaqueType);


/* FOLLOW(procedureType) */

m2c_tokenset_t procedureType = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_END, 0
);

PRINT_LITERAL("procedureType", procedureType);


/* FOLLOW(formalType) */

m2c_tokenset_t formalType = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_RPAREN, 0
);

PRINT_LITERAL("formalType", formalType);


/* FOLLOW(nonAttrFormalType) */

m2c_tokenset_t nonAttrFormalType = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_RPAREN, 0
);

PRINT_LITERAL("nonAttrFormalType", nonAttrFormalType);


/* FOLLOW(simpleFormalType) */

m2c_tokenset_t simpleFormalType = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_RPAREN, 0
);

PRINT_LITERAL("simpleFormalType", simpleFormalType);


/* FOLLOW(castingFormalType) */

m2c_tokenset_t castingFormalType = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_RPAREN, 0
);

PRINT_LITERAL("castingFormalType", castingFormalType);


/* FOLLOW(variadicFormalType) */

m2c_tokenset_t variadicFormalType = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_RPAREN, 0
);

PRINT_LITERAL("variadicFormalType", variadicFormalType);


/* FOLLOW(procedureHeader) */

m2c_tokenset_t procedureHeader = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, 0
);

PRINT_LITERAL("procedureHeader", procedureHeader);


/* FOLLOW(bindingSpecifier) */

m2c_tokenset_t bindingSpecifier = m2c_new_tokenset_from_list(
  TOKEN_RBRACKET, 0
);

PRINT_LITERAL("bindingSpecifier", bindingSpecifier);


/* FOLLOW(bindableIdent) */

m2c_tokenset_t bindableIdent = m2c_new_tokenset_from_list(
  TOKEN_RBRACKET, 0
);

PRINT_LITERAL("bindableIdent", bindableIdent);


/* FOLLOW(procedureSignature) */

m2c_tokenset_t procedureSignature = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, 0
);

PRINT_LITERAL("procedureSignature", procedureSignature);


/* FOLLOW(formalParams) */

m2c_tokenset_t formalParams = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_RPAREN, 0
);

PRINT_LITERAL("formalParams", formalParams);


/* FOLLOW(programModule) */

m2c_tokenset_t programModule = m2c_new_tokenset_from_list(
  TOKEN_EOF, 0
);

PRINT_LITERAL("programModule", programModule);


/* FOLLOW(privateImport) */

m2c_tokenset_t privateImport = m2c_new_tokenset_from_list(
  TOKEN_IMPORT, TOKEN_CONST, TOKEN_TYPE, TOKEN_VAR, TOKEN_PROCEDURE,
  TOKEN_UNQUALIFIED, TOKEN_TO, TOKEN_BEGIN, TOKEN_END, 0
);

PRINT_LITERAL("privateImport", privateImport);


/* FOLLOW(block) */

m2c_tokenset_t block = m2c_new_tokenset_from_list(
  TOKEN_IDENT, 0
);

PRINT_LITERAL("block", block);


/* FOLLOW(implementationModule) */

m2c_tokenset_t implementationModule = m2c_new_tokenset_from_list(
  TOKEN_EOF, 0
);

PRINT_LITERAL("implementationModule", implementationModule);


/* FOLLOW(possiblyEmptyBlock) */

m2c_tokenset_t possiblyEmptyBlock = m2c_new_tokenset_from_list(
  TOKEN_IDENT, 0
);

PRINT_LITERAL("possiblyEmptyBlock", possiblyEmptyBlock);


/* FOLLOW(declaration) */

m2c_tokenset_t declaration = m2c_new_tokenset_from_list(
  TOKEN_CONST, TOKEN_TYPE, TOKEN_VAR, TOKEN_PROCEDURE, TOKEN_UNQUALIFIED,
  TOKEN_TO, TOKEN_BEGIN, 0
);

PRINT_LITERAL("declaration", declaration);


/* FOLLOW(typeDeclaration) */

m2c_tokenset_t typeDeclaration = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, 0
);

PRINT_LITERAL("typeDeclaration", typeDeclaration);


/* FOLLOW(octetSeqType) */

m2c_tokenset_t octetSeqType = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, 0
);

PRINT_LITERAL("octetSeqType", octetSeqType);


/* FOLLOW(privatePointerType) */

m2c_tokenset_t privatePointerType = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, 0
);

PRINT_LITERAL("privatePointerType", privatePointerType);


/* FOLLOW(indeterminateTarget) */

m2c_tokenset_t indeterminateTarget = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, 0
);

PRINT_LITERAL("indeterminateTarget", indeterminateTarget);


/* FOLLOW(indeterminateField) */

m2c_tokenset_t indeterminateField = m2c_new_tokenset_from_list(
  TOKEN_END, 0
);

PRINT_LITERAL("indeterminateField", indeterminateField);


/* FOLLOW(varDeclaration) */

m2c_tokenset_t varDeclaration = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, 0
);

PRINT_LITERAL("varDeclaration", varDeclaration);


/* FOLLOW(aliasDeclaration) */

m2c_tokenset_t aliasDeclaration = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, 0
);

PRINT_LITERAL("aliasDeclaration", aliasDeclaration);


/* FOLLOW(nameSelector) */

m2c_tokenset_t nameSelector = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_COMMA, 0
);

PRINT_LITERAL("nameSelector", nameSelector);


/* FOLLOW(statementSeqence) */

m2c_tokenset_t statementSeqence = m2c_new_tokenset_from_list(
  TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END, TOKEN_BAR, TOKEN_UNTIL, 0
);

PRINT_LITERAL("statementSeqence", statementSeqence);


/* FOLLOW(statement) */

m2c_tokenset_t statement = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END, TOKEN_BAR,
  TOKEN_UNTIL, 0
);

PRINT_LITERAL("statement", statement);


/* FOLLOW(memMgtOperation) */

m2c_tokenset_t memMgtOperation = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END, TOKEN_BAR,
  TOKEN_UNTIL, 0
);

PRINT_LITERAL("memMgtOperation", memMgtOperation);


/* FOLLOW(newStatement) */

m2c_tokenset_t newStatement = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END, TOKEN_BAR,
  TOKEN_UNTIL, 0
);

PRINT_LITERAL("newStatement", newStatement);


/* FOLLOW(retainStatement) */

m2c_tokenset_t retainStatement = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END, TOKEN_BAR,
  TOKEN_UNTIL, 0
);

PRINT_LITERAL("retainStatement", retainStatement);


/* FOLLOW(releaseStatement) */

m2c_tokenset_t releaseStatement = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END, TOKEN_BAR,
  TOKEN_UNTIL, 0
);

PRINT_LITERAL("releaseStatement", releaseStatement);


/* FOLLOW(updateOrProcCall) */

m2c_tokenset_t updateOrProcCall = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END, TOKEN_BAR,
  TOKEN_UNTIL, 0
);

PRINT_LITERAL("updateOrProcCall", updateOrProcCall);


/* FOLLOW(incOrDecSuffix) */

m2c_tokenset_t incOrDecSuffix = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END, TOKEN_BAR,
  TOKEN_UNTIL, 0
);

PRINT_LITERAL("incOrDecSuffix", incOrDecSuffix);


/* FOLLOW(returnStatement) */

m2c_tokenset_t returnStatement = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END, TOKEN_BAR,
  TOKEN_UNTIL, 0
);

PRINT_LITERAL("returnStatement", returnStatement);


/* FOLLOW(copyStatement) */

m2c_tokenset_t copyStatement = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END, TOKEN_BAR,
  TOKEN_UNTIL, 0
);

PRINT_LITERAL("copyStatement", copyStatement);


/* FOLLOW(readStatement) */

m2c_tokenset_t readStatement = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END, TOKEN_BAR,
  TOKEN_UNTIL, 0
);

PRINT_LITERAL("readStatement", readStatement);


/* FOLLOW(writeStatement) */

m2c_tokenset_t writeStatement = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END, TOKEN_BAR,
  TOKEN_UNTIL, 0
);

PRINT_LITERAL("readStatement", readStatement);


/* FOLLOW(inputArg) */

m2c_tokenset_t inputArg = m2c_new_tokenset_from_list(
  TOKEN_COMMA, TOKEN_SEMICOLON, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END,
  TOKEN_BAR, TOKEN_UNTIL, 0
);

PRINT_LITERAL("inputArg", inputArg);


/* FOLLOW(outputArgs) */

m2c_tokenset_t outputArgs = m2c_new_tokenset_from_list(
  TOKEN_COMMA, TOKEN_SEMICOLON, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END,
  TOKEN_BAR, TOKEN_UNTIL, 0
);

PRINT_LITERAL("outputArgs", outputArgs);


/* FOLLOW(formattedArgs) */

m2c_tokenset_t formattedArgs = m2c_new_tokenset_from_list(
  TOKEN_COMMA, TOKEN_SEMICOLON, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END,
  TOKEN_BAR, TOKEN_UNTIL, 0
);

PRINT_LITERAL("formattedArgs", formattedArgs);


/* FOLLOW(ifStatement) */

m2c_tokenset_t ifStatement = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END, TOKEN_BAR,
  TOKEN_UNTIL, 0
);

PRINT_LITERAL("ifStatement", ifStatement);


/* FOLLOW(caseStatement) */

m2c_tokenset_t caseStatement = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END, TOKEN_BAR,
  TOKEN_UNTIL, 0
);

PRINT_LITERAL("caseStatement", caseStatement);


/* FOLLOW(case) */

m2c_tokenset_t case_ = m2c_new_tokenset_from_list(
  TOKEN_BAR, TOKEN_ELSE, TOKEN_END, 0
);

PRINT_LITERAL("case", case_);


/* FOLLOW(caseLabels) */

m2c_tokenset_t caseLabels = m2c_new_tokenset_from_list(
  TOKEN_COMMA, TOKEN_SEMICOLON, 0
);

PRINT_LITERAL("caseLabels", caseLabels);


/* FOLLOW(loopStatement) */

m2c_tokenset_t loopStatement = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END, TOKEN_BAR,
  TOKEN_UNTIL, 0
);

PRINT_LITERAL("loopStatement", loopStatement);


/* FOLLOW(whileStatement) */

m2c_tokenset_t whileStatement = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END, TOKEN_BAR,
  TOKEN_UNTIL, 0
);

PRINT_LITERAL("whileStatement", whileStatement);


/* FOLLOW(repeatStatement) */

m2c_tokenset_t repeatStatement = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END, TOKEN_BAR,
  TOKEN_UNTIL, 0
);

PRINT_LITERAL("repeatStatement", repeatStatement);


/* FOLLOW(forStatement) */

m2c_tokenset_t forStatement = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END, TOKEN_BAR,
  TOKEN_UNTIL, 0
);

PRINT_LITERAL("forStatement", forStatement);


/* FOLLOW(forLoopVariants) */

m2c_tokenset_t forLoopVariants = m2c_new_tokenset_from_list(
  TOKEN_IN, 0
);

PRINT_LITERAL("forLoopVariants", forLoopVariants);


/* FOLLOW(iterableExpr) */

m2c_tokenset_t iterableExpr = m2c_new_tokenset_from_list(
  TOKEN_DO, 0
);

PRINT_LITERAL("iterableExpr", iterableExpr);


/* FOLLOW(valueRange) */

m2c_tokenset_t valueRange = m2c_new_tokenset_from_list(
  TOKEN_DO, 0
);

PRINT_LITERAL("valueRange", valueRange);


/* FOLLOW(designator) */

m2c_tokenset_t designator = m2c_new_tokenset_from_list(
  TOKEN_ASSIGN, TOKEN_IDENT, TOKEN_SEMICOLON, TOKEN_ELSIF, TOKEN_ELSE,
  TOKEN_END, TOKEN_BAR, TOKEN_UNTIL, TOKEN_PLUS_PLUS, TOKEN_MINUS_MINUS,
  TOKEN_LPAREN, TOKEN_COLON, 0
);

PRINT_LITERAL("designator", designator);


/* FOLLOW(derefTail) */

m2c_tokenset_t derefTail = m2c_new_tokenset_from_list(
  TOKEN_ASSIGN, TOKEN_IDENT, TOKEN_SEMICOLON, TOKEN_ELSIF, TOKEN_ELSE,
  TOKEN_END, TOKEN_BAR, TOKEN_UNTIL, TOKEN_PLUS_PLUS, TOKEN_MINUS_MINUS,
  TOKEN_LPAREN, TOKEN_COLON, 0
);

PRINT_LITERAL("derefTail", derefTail);


/* FOLLOW(subscriptTail) */

m2c_tokenset_t subscriptTail = m2c_new_tokenset_from_list(
  TOKEN_ASSIGN, TOKEN_IDENT, TOKEN_SEMICOLON, TOKEN_ELSIF, TOKEN_ELSE,
  TOKEN_END, TOKEN_BAR, TOKEN_UNTIL, TOKEN_PLUS_PLUS, TOKEN_MINUS_MINUS,
  TOKEN_LPAREN, TOKEN_COLON, 0
);

PRINT_LITERAL("subscriptTail", subscriptTail);


/* FOLLOW(targetDesignator) */

m2c_tokenset_t targetDesignator = m2c_new_tokenset_from_list(
  TOKEN_ASSIGN, 0
);

PRINT_LITERAL("targetDesignator", targetDesignator);


/* FOLLOW(derefTargetTail) */

m2c_tokenset_t derefTargetTail = m2c_new_tokenset_from_list(
  TOKEN_ASSIGN, 0
);

PRINT_LITERAL("derefTargetTail", derefTargetTail);


/* FOLLOW(bracketTargetTail) */

m2c_tokenset_t bracketTargetTail = m2c_new_tokenset_from_list(
  TOKEN_ASSIGN, 0
);

PRINT_LITERAL("bracketTargetTail", bracketTargetTail);


/* FOLLOW(deref) */

m2c_tokenset_t deref = m2c_new_tokenset_from_list(
  TOKEN_DEREF, TOKEN_DOT, TOKEN_LBRACKET, TOKEN_ASSIGN, 0
);

PRINT_LITERAL("deref", deref);


/* FOLLOW(expressionList) */

m2c_tokenset_t expressionList = m2c_new_tokenset_from_list(
  TOKEN_COMMA, TOKEN_COLON, TOKEN_SEMICOLON, TOKEN_DOT_DOT, TOKEN_RBRACKET,
  TOKEN_RPAREN, TOKEN_RBRACE, TOKEN_OF, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END,
  TOKEN_BAR, TOKEN_UNTIL, TOKEN_THEN, TOKEN_DO, 0
);

PRINT_LITERAL("expressionList", expressionList);


/* FOLLOW(expression) */

m2c_tokenset_t expression = m2c_new_tokenset_from_list(
  TOKEN_COMMA, TOKEN_COLON, TOKEN_SEMICOLON, TOKEN_DOT_DOT, TOKEN_RBRACKET,
  TOKEN_RPAREN, TOKEN_RBRACE, TOKEN_OF, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END,
  TOKEN_BAR, TOKEN_UNTIL, TOKEN_THEN, TOKEN_DO, 0
);

PRINT_LITERAL("expression", expression);


/* FOLLOW(operL1) */

m2c_tokenset_t operL1 = m2c_new_tokenset_from_list(
  TOKEN_NOT, TOKEN_WHOLE_NUMBER, TOKEN_REAL_NUMBER, TOKEN_CHAR_CODE,
  TOKEN_QUOTED_STRING, TOKEN_LBRACE, TOKEN_IDENT, TOKEN_LPAREN,
  TOKEN_ASTERISK, TOKEN_SOLIDUS, TOKEN_DIV, TOKEN_MOD, TOKEN_AND,
  TOKEN_MINUS, 0
);

PRINT_LITERAL("operL1", operL1);


/* FOLLOW(simpleExpression) */

m2c_tokenset_t simpleExpression = m2c_new_tokenset_from_list(
  TOKEN_COMMA, TOKEN_COLON, TOKEN_SEMICOLON, TOKEN_DOT_DOT, TOKEN_RBRACKET,
  TOKEN_RPAREN, TOKEN_RBRACE, TOKEN_OF, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END,
  TOKEN_BAR, TOKEN_UNTIL, TOKEN_THEN, TOKEN_DO, 0
);

PRINT_LITERAL("simpleExpression", simpleExpression);


/* FOLLOW(operL2) */

m2c_tokenset_t operL2 = m2c_new_tokenset_from_list(
  TOKEN_NOT, TOKEN_WHOLE_NUMBER, TOKEN_REAL_NUMBER, TOKEN_CHAR_CODE,
  TOKEN_QUOTED_STRING, TOKEN_LBRACE, TOKEN_IDENT, TOKEN_LPAREN,
  TOKEN_ASTERISK, TOKEN_SOLIDUS, TOKEN_DIV, TOKEN_MOD, TOKEN_AND, 0
);

PRINT_LITERAL("operL2", operL2);


/* FOLLOW(term) */

m2c_tokenset_t term = m2c_new_tokenset_from_list(
  TOKEN_PLUS, TOKEN_MINUS, TOKEN_OR, TOKEN_CONCAT, TOKEN_SET_DIFF,
  TOKEN_COMMA, TOKEN_COLON, TOKEN_SEMICOLON, TOKEN_DOT_DOT, TOKEN_RBRACKET,
  TOKEN_RPAREN, TOKEN_RBRACE, TOKEN_OF, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END,
  TOKEN_BAR, TOKEN_UNTIL, TOKEN_THEN, TOKEN_DO, 0
);

PRINT_LITERAL("term", term);


/* FOLLOW(operL3) */

m2c_tokenset_t operL3 = m2c_new_tokenset_from_list(
  TOKEN_NOT, TOKEN_WHOLE_NUMBER, TOKEN_REAL_NUMBER, TOKEN_CHAR_CODE,
  TOKEN_QUOTED_STRING, TOKEN_LBRACE, TOKEN_IDENT, TOKEN_LPAREN, 0
);

PRINT_LITERAL("operL3", operL3);


/* FOLLOW(simpleTerm) */

m2c_tokenset_t simpleTerm = m2c_new_tokenset_from_list(
  TOKEN_ASTERISK, TOKEN_SOLIDUS, TOKEN_DIV, TOKEN_MOD, TOKEN_AND,
  TOKEN_PLUS, TOKEN_MINUS, TOKEN_OR, TOKEN_CONCAT, TOKEN_SET_DIFF,
  TOKEN_COMMA, TOKEN_COLON, TOKEN_SEMICOLON, TOKEN_DOT_DOT, TOKEN_RBRACKET,
  TOKEN_RPAREN, TOKEN_RBRACE, TOKEN_OF, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END,
  TOKEN_BAR, TOKEN_UNTIL, TOKEN_THEN, TOKEN_DO, 0
);

PRINT_LITERAL("simpleTerm", simpleTerm);


/* FOLLOW(factor) */

m2c_tokenset_t factor = m2c_new_tokenset_from_list(
  TOKEN_COMMA, TOKEN_COLON, TOKEN_SEMICOLON, TOKEN_DOT_DOT, TOKEN_RBRACKET,
  TOKEN_RPAREN, TOKEN_RBRACE, TOKEN_ASTERISK, TOKEN_SOLIDUS, TOKEN_DIV,
  TOKEN_MOD, TOKEN_AND, TOKEN_PLUS, TOKEN_MINUS, TOKEN_OR, TOKEN_CONCAT,
  TOKEN_SET_DIFF, TOKEN_OF, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END, TOKEN_BAR,
  TOKEN_UNTIL, TOKEN_THEN, TOKEN_DO, 0
);

PRINT_LITERAL("factor", factor);


/* FOLLOW(simpleFactor) */

m2c_tokenset_t simpleFactor = m2c_new_tokenset_from_list(
  TOKEN_CONV, TOKEN_COMMA, TOKEN_COLON, TOKEN_SEMICOLON, TOKEN_DOT_DOT,
  TOKEN_RBRACKET, TOKEN_RPAREN, TOKEN_RBRACE, TOKEN_ASTERISK, TOKEN_SOLIDUS,
  TOKEN_DIV, TOKEN_MOD, TOKEN_AND, TOKEN_PLUS, TOKEN_MINUS, TOKEN_OR,
  TOKEN_CONCAT, TOKEN_SET_DIFF, TOKEN_OF, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END,
  TOKEN_BAR, TOKEN_UNTIL, TOKEN_THEN, TOKEN_DO, 0
);

PRINT_LITERAL("simpleFactor", simpleFactor);


/* FOLLOW(sourceDesignator) */

m2c_tokenset_t sourceDesignator = m2c_new_tokenset_from_list(
  TOKEN_CONV, TOKEN_COMMA, TOKEN_COLON, TOKEN_SEMICOLON, TOKEN_DOT_DOT,
  TOKEN_RBRACKET, TOKEN_RPAREN, TOKEN_RBRACE, TOKEN_ASTERISK, TOKEN_SOLIDUS,
  TOKEN_DIV, TOKEN_MOD, TOKEN_AND, TOKEN_PLUS, TOKEN_MINUS, TOKEN_OR,
  TOKEN_CONCAT, TOKEN_SET_DIFF, TOKEN_OF, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END,
  TOKEN_BAR, TOKEN_UNTIL, TOKEN_THEN, TOKEN_DO, 0
);

PRINT_LITERAL("sourceDesignator", sourceDesignator);


/* FOLLOW(derefSourceTail) */

m2c_tokenset_t derefSourceTail = m2c_new_tokenset_from_list(
  TOKEN_CONV, TOKEN_COMMA, TOKEN_COLON, TOKEN_SEMICOLON, TOKEN_DOT_DOT,
  TOKEN_RBRACKET, TOKEN_RPAREN, TOKEN_RBRACE, TOKEN_ASTERISK, TOKEN_SOLIDUS,
  TOKEN_DIV, TOKEN_MOD, TOKEN_AND, TOKEN_PLUS, TOKEN_MINUS, TOKEN_OR,
  TOKEN_CONCAT, TOKEN_SET_DIFF, TOKEN_OF, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END,
  TOKEN_BAR, TOKEN_UNTIL, TOKEN_THEN, TOKEN_DO, 0
);

PRINT_LITERAL("sourceDesignator", sourceDesignator);


/* FOLLOW(bracketSourceTail) */

m2c_tokenset_t bracketSourceTail = m2c_new_tokenset_from_list(
  TOKEN_CONV, TOKEN_COMMA, TOKEN_COLON, TOKEN_SEMICOLON, TOKEN_DOT_DOT,
  TOKEN_RBRACKET, TOKEN_RPAREN, TOKEN_RBRACE, TOKEN_ASTERISK, TOKEN_SOLIDUS,
  TOKEN_DIV, TOKEN_MOD, TOKEN_AND, TOKEN_PLUS, TOKEN_MINUS, TOKEN_OR,
  TOKEN_CONCAT, TOKEN_SET_DIFF, TOKEN_OF, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END,
  TOKEN_BAR, TOKEN_UNTIL, TOKEN_THEN, TOKEN_DO, 0
);

PRINT_LITERAL("bracketSourceTail", bracketSourceTail);


/* FOLLOW(functionCallTail) */

m2c_tokenset_t functionCallTail = m2c_new_tokenset_from_list(
  TOKEN_CONV, TOKEN_COMMA, TOKEN_COLON, TOKEN_SEMICOLON, TOKEN_DOT_DOT,
  TOKEN_RBRACKET, TOKEN_RPAREN, TOKEN_RBRACE, TOKEN_ASTERISK, TOKEN_SOLIDUS,
  TOKEN_DIV, TOKEN_MOD, TOKEN_AND, TOKEN_PLUS, TOKEN_MINUS, TOKEN_OR,
  TOKEN_CONCAT, TOKEN_SET_DIFF, TOKEN_OF, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END,
  TOKEN_BAR, TOKEN_UNTIL, TOKEN_THEN, TOKEN_DO, 0
);

PRINT_LITERAL("functionCallTail", functionCallTail);


/* FOLLOW(structuredValue) */

m2c_tokenset_t structuredValue = m2c_new_tokenset_from_list(
  TOKEN_CONV, TOKEN_COMMA, TOKEN_COLON, TOKEN_SEMICOLON, TOKEN_DOT_DOT,
  TOKEN_RBRACKET, TOKEN_RPAREN, TOKEN_RBRACE, TOKEN_ASTERISK, TOKEN_SOLIDUS,
  TOKEN_DIV, TOKEN_MOD, TOKEN_AND, TOKEN_PLUS, TOKEN_MINUS, TOKEN_OR,
  TOKEN_CONCAT, TOKEN_SET_DIFF, TOKEN_OF, TOKEN_ELSIF, TOKEN_ELSE, TOKEN_END,
  TOKEN_BAR, TOKEN_UNTIL, TOKEN_THEN, TOKEN_DO, 0
);

PRINT_LITERAL("structuredValue", structuredValue);


/* FOLLOW(valueComponent) */

m2c_tokenset_t valueComponent = m2c_new_tokenset_from_list(
  TOKEN_COMMA, TOKEN_RBRACE, 0
);

PRINT_LITERAL("valueComponent", valueComponent);


/* FOLLOW(toDoList) */

m2c_tokenset_t toDoList = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, 0
);

PRINT_LITERAL("toDoList", toDoList);


/* FOLLOW(trackingRef) */

m2c_tokenset_t trackingRef = m2c_new_tokenset_from_list(
  TOKEN_QUOTED_STRING, 0
);

PRINT_LITERAL("trackingRef", trackingRef);


/* FOLLOW(taskToDo) */

m2c_tokenset_t taskToDo = m2c_new_tokenset_from_list(
  TOKEN_SEMICOLON, TOKEN_END, 0
);

PRINT_LITERAL("taskToDo", taskToDo);


PRINT_EOF;
} /* end main */

/* END OF FILE */