/* AUTO-GENERATED by utility gen-pruned-follow-sets * DO NOT EDIT! */

DATA(IMPORT /* name-index: 2 */, /* data-index: 1 */ (
    { /* bits: */ 0x00084080, 0x00002601, 0x00000000, /* counter: */ 7 }
  )
)
DATA(DEFINITION /* name-index: 3 */, /* data-index: 2 */ (
    { /* bits: */ 0x00000080, 0x00002601, 0x00000000, /* counter: */ 5 }
  )
)
DATA(CONST_EXPRESSION /* name-index: 7 */, /* data-index: 3 */ (
    { /* bits: */ 0x10000000, 0x04E00000, 0x00000014, /* counter: */ 7 }
  )
)
DATA(QUALIDENT /* name-index: 10 */, /* data-index: 4 */ (
    { /* bits: */ 0x00004800, 0xC0A00000, 0x00180003, /* counter: */ 10 }
  )
)
DATA(SUBRANGE_TYPE /* name-index: 11 */, /* data-index: 5 */ (
    { /* bits: */ 0x00004000, 0x00800000, 0x00000000, /* counter: */ 2 }
  )
)
DATA(IDENT_LIST /* name-index: 14 */, /* data-index: 6 */ (
    { /* bits: */ 0x00000000, 0x00400000, 0x00000001, /* counter: */ 2 }
  )
)
DATA(FORMAL_TYPE /* name-index: 23 */, /* data-index: 7 */ (
    { /* bits: */ 0x00000000, 0x00800000, 0x00000001, /* counter: */ 2 }
  )
)
DATA(PRIVATE_IMPORT /* name-index: 34 */, /* data-index: 8 */ (
    { /* bits: */ 0x000840A0, 0x00002E01, 0x00000000, /* counter: */ 9 }
  )
)
DATA(DECLARATION /* name-index: 38 */, /* data-index: 9 */ (
    { /* bits: */ 0x000000A0, 0x00002E01, 0x00000000, /* counter: */ 7 }
  )
)
DATA(STATEMENT_SEQUENCE /* name-index: 47 */, /* data-index: 10 */ (
    { /* bits: */ 0x00007000, 0x02001000, 0x00000000, /* counter: */ 5 }
  )
)
DATA(STATEMENT /* name-index: 48 */, /* data-index: 11 */ (
    { /* bits: */ 0x00007000, 0x02801000, 0x00000000, /* counter: */ 6 }
  )
)
DATA(INPUT_ARG /* name-index: 59 */, /* data-index: 12 */ (
    { /* bits: */ 0x00007000, 0x02A01000, 0x00000000, /* counter: */ 7 }
  )
)
DATA(CASE /* name-index: 64 */, /* data-index: 13 */ (
    { /* bits: */ 0x00005000, 0x02000000, 0x00000000, /* counter: */ 3 }
  )
)
DATA(CASE_LABELS /* name-index: 65 */, /* data-index: 14 */ (
    { /* bits: */ 0x00000000, 0x00A00000, 0x00000000, /* counter: */ 2 }
  )
)
DATA(DESIGNATOR /* name-index: 73 */, /* data-index: 15 */ (
    { /* bits: */ 0x00007000, 0xBAC11000, 0x00000000, /* counter: */ 12 }
  )
)
DATA(DEREF /* name-index: 79 */, /* data-index: 16 */ (
    { /* bits: */ 0x00000000, 0x08000000, 0x00180002, /* counter: */ 4 }
  )
)
DATA(EXPRESSION_LIST /* name-index: 80 */, /* data-index: 17 */ (
    { /* bits: */ 0x10007800, 0x06E01100, 0x00000015, /* counter: */ 15 }
  )
)
DATA(OPER_L1 /* name-index: 82 */, /* data-index: 18 */ (
    { /* bits: */ 0x04400404, 0x801F0000, 0x00032008, /* counter: */ 14 }
  )
)
DATA(OPER_L2 /* name-index: 84 */, /* data-index: 19 */ (
    { /* bits: */ 0x04400404, 0x801F0000, 0x00030008, /* counter: */ 13 }
  )
)
DATA(TERM /* name-index: 85 */, /* data-index: 20 */ (
    { /* bits: */ 0x50007800, 0x06E01100, 0x0000F015, /* counter: */ 20 }
  )
)
DATA(OPER_L3 /* name-index: 86 */, /* data-index: 21 */ (
    { /* bits: */ 0x04000000, 0x801F0000, 0x00000008, /* counter: */ 8 }
  )
)
DATA(SIMPLE_TERM /* name-index: 87 */, /* data-index: 22 */ (
    { /* bits: */ 0x50407C04, 0x06E01100, 0x0003F015, /* counter: */ 25 }
  )
)
DATA(SIMPLE_FACTOR /* name-index: 89 */, /* data-index: 23 */ (
    { /* bits: */ 0x50407C04, 0x06E01100, 0x0007F015, /* counter: */ 26 }
  )
)

/* END OF FILE */
