/* AUTO-GENERATED by utility gen-pruned-first-sets * DO NOT EDIT! */

DATA(COMPILATION_UNIT /* name-index: 0 */, /* data-index: 1 */ (
    { /* bits: */ 0x00840200, 0x00000000, 0x00000000, /* counter: */ 3 }
  )
),
DATA(DEFINITION /* name-index: 3 */, /* data-index: 2 */ (
    { /* bits: */ 0x00000080, 0x00002601, 0x00000000, /* counter: */ 5 }
  )
),
DATA(CONST_DEFINITION /* name-index: 4 */, /* data-index: 3 */ (
    { /* bits: */ 0x00000000, 0x00010000, 0x00000002, /* counter: */ 2 }
  )
),
DATA(CONST_EXPRESSION /* name-index: 7 */, /* data-index: 4 */ (
    { /* bits: */ 0x04400404, 0x801F0000, 0x00032008, /* counter: */ 14 }
  )
),
DATA(FORMAL_TYPE /* name-index: 23 */, /* data-index: 5 */ (
    { /* bits: */ 0x00000098, 0x00012000, 0x00000000, /* counter: */ 5 }
  )
),
DATA(NON_ATTR_FORMAL_TYPE /* name-index: 24 */, /* data-index: 6 */ (
    { /* bits: */ 0x00000018, 0x00010000, 0x00000000, /* counter: */ 3 }
  )
),
DATA(SIMPLE_FORMAL_TYPE /* name-index: 25 */, /* data-index: 7 */ (
    { /* bits: */ 0x00000010, 0x00010000, 0x00000000, /* counter: */ 2 }
  )
),
DATA(BINDING_SPECIFIER /* name-index: 29 */, /* data-index: 8 */ (
    { /* bits: */ 0x01000000, 0x0001802A, 0x00000000, /* counter: */ 6 }
  )
),
DATA(FORMAL_PARAMS /* name-index: 32 */, /* data-index: 9 */ (
    { /* bits: */ 0x00000080, 0x00012000, 0x00000000, /* counter: */ 3 }
  )
),
DATA(BLOCK /* name-index: 35 */, /* data-index: 10 */ (
    { /* bits: */ 0x000000A0, 0x00002E01, 0x00000000, /* counter: */ 7 }
  )
),
DATA(POSSIBLY_EMPTY_BLOCK /* name-index: 37 */, /* data-index: 11 */ (
    { /* bits: */ 0x000040A0, 0x00002E01, 0x00000000, /* counter: */ 8 }
  )
),
DATA(DECLARATION /* name-index: 38 */, /* data-index: 12 */ (
    { /* bits: */ 0x00000080, 0x00002E01, 0x00000000, /* counter: */ 6 }
  )
),
DATA(STATEMENT_SEQUENCE /* name-index: 47 */, /* data-index: 13 */ (
    { /* bits: */ 0x03238140, 0x0001C27A, 0x00000000, /* counter: */ 17 }
  )
),
DATA(MEM_MGT_OPERATION /* name-index: 49 */, /* data-index: 14 */ (
    { /* bits: */ 0x01000000, 0x00000028, 0x00000000, /* counter: */ 3 }
  )
),
DATA(INC_OR_DEC_SUFFIX /* name-index: 54 */, /* data-index: 15 */ (
    { /* bits: */ 0x00000000, 0x30000000, 0x00000000, /* counter: */ 2 }
  )
),
DATA(INPUT_ARG /* name-index: 59 */, /* data-index: 16 */ (
    { /* bits: */ 0x01000000, 0x00010000, 0x00000000, /* counter: */ 2 }
  )
),
DATA(OUTPUT_ARGS /* name-index: 60 */, /* data-index: 17 */ (
    { /* bits: */ 0x04000000, 0x801F0000, 0x00002048, /* counter: */ 10 }
  )
),
DATA(CASE /* name-index: 64 */, /* data-index: 18 */ (
    { /* bits: */ 0x04000000, 0x801F0000, 0x00002008, /* counter: */ 9 }
  )
),
DATA(OPER_L1 /* name-index: 82 */, /* data-index: 19 */ (
    { /* bits: */ 0x00100000, 0x00000000, 0x00000FE0, /* counter: */ 8 }
  )
),
DATA(OPER_L2 /* name-index: 84 */, /* data-index: 20 */ (
    { /* bits: */ 0x40000000, 0x00000000, 0x0000F000, /* counter: */ 5 }
  )
),
DATA(TERM /* name-index: 85 */, /* data-index: 21 */ (
    { /* bits: */ 0x04000000, 0x801F0000, 0x00000008, /* counter: */ 8 }
  )
),
DATA(OPER_L3 /* name-index: 86 */, /* data-index: 22 */ (
    { /* bits: */ 0x00400404, 0x00000000, 0x00030000, /* counter: */ 5 }
  )
),

/* END OF FILE */
